### ISSUE TITLE
Owntracks not correct working with Homey 2.0

### ISSUE THREAD

**Issue by FrankRinkens** [scanno/nl.scanno.owntracks#1]
Owntracks is logging / complaining broker isn’t there and a second later broker is there again. This is repeating +/- every half hour. You can see it on the startpage of homey, this can't be solve with settings. seems owntracks isn't compatible with Homey 2.0 and CloudMQTT.

Messige in dutch: 

De MQTT broker is ONBESCHIKBAAR 

a second or two later this message appears:

De MQTT broker is BESCHIKBAAR

best regards,
Frank

**Comment by scanno** [comment]
Owntracks is not really incompatible with homey v2 because i have been running it for a long time on Homey v2 without any problems. However since i updated the MQTT client libraries in the recent owntracks update, the problem is more likely due to the MQTT client update.

At the moment there is a version 2.2.2 of the owntracks pending approval that add a new configuration variable (keepalive) that can be set.

The problem you are facing is due to the fact that CloudMQTT does not receive a keepalive request within the specified time. By default the keepalive is set to 10 seconds. When the broker does not receive a keepalive request from owntracks within 1.5 times the keepalive value (default 15 seconds), the connection is dropped by the broker (thats in the protocol specifications and what another user was told by the CloudMQTT helpdesk). So somehow the keepalive request is not received within 15 seconds.
Why this is happening is yet unknown, but that can be due to Homey being busy or unstable network.

As said i have introduced the keepalive setting and the default is raised from 10 seconds to 60 seconds in version 2.2.2. If the problem still exists after you received the update, please try increasing the keepalive value and see if that solves the problem.

**Comment by FrankRinkens** [comment]
Ok many thanks. Sounds like this is going to solve the problem.

**Comment by scanno** [comment]
Version 2.2.2 is published

**Comment by FrankRinkens** [comment]
Ok thanks and installed, but where tot set this keep alive message exactly?

**Comment by FrankRinkens** [comment]
Ok. Sorry found it. It's an empty field by default in the app.

**Comment by FrankRinkens** [comment]
If a user leaves a geofence the trigger is on "Geofence In" and the other way around. If a user comes a geo in a geofence out trigger is activated. So something is wrong here it works like the opposite trigger. I'm the only one who have/sees this?

**Comment by scanno** [comment]
Have not seen anything like that. Did you enable the location events option by any chance?

**Comment by FrankRinkens** [comment]
Move mode is enabled dual arrow >> is this not allowed? can test with only one arrow > significant changes only if you want

**Comment by scanno** [comment]
No i mean in the homey owntracks app.
![image](https://user-images.githubusercontent.com/637981/50483083-5a178980-09ea-11e9-9755-06401f1aa24a.png)
If its enabled, please disable it.

The logic regarding enter / leave events has not been touched for a while, just the location events and that new option should be disabled by default.

But if that happens, please give me some logging from the homey owntracks app so i can see if there is anything.

**Comment by FrankRinkens** [comment]
no, that option isn't enabled. strange thing is it has worked before with the flows I have. Now I see the oppisite happening as described. Getting crazy on this.... will do additional tests.

**Comment by scanno** [comment]
> no, that option isn't enabled. strange thing is it has worked before with the flows I have. Now I see the oppisite happening as described. Getting crazy on this.... will do additional tests.

It should be working with the flows you have. It does here. So please some logging if you have the problem

**Comment by FrankRinkens** [comment]
Hi the problem is in the client on the phone. I deleted and created the region again. now it seems to work. Should I keep the owntracks client on the phone open in the background? or should it work when the app is completely closed? problem I'm experiencing is that it isn't reliable at the moment.

and another question I have is: in the logging I see state.topic = owntracks\.......\event topic = undefined what does that mean?

**Comment by FrankRinkens** [comment]
There is no answer on my Question? I tested a lot now for over a week and it works but isn't consistent. If the app is open in the background you have the most chance that it works. You can close this topic if you want. thanks.

**Comment by scanno** [comment]
Sry my free time is a bit limited.
What is not consistent? The reporting of the owntracks phone app? Well problem mostly is that depending on the phone and os, the app can be put on hold so the location is not send to homey. You can tweak thing ls in the phone app. 
Setting the phone app to move mode will give you the best results, but will cost you more battery usage.
